/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UploadsRouteImport } from './routes/uploads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/editor': typeof EditorRoute
  '/games': typeof GamesRoute
  '/library': typeof LibraryRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/uploads': typeof UploadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/editor': typeof EditorRoute
  '/games': typeof GamesRoute
  '/library': typeof LibraryRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/uploads': typeof UploadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/editor': typeof EditorRoute
  '/games': typeof GamesRoute
  '/library': typeof LibraryRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/uploads': typeof UploadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/diagnostics'
    | '/editor'
    | '/games'
    | '/library'
    | '/recordings'
    | '/settings'
    | '/uploads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/diagnostics'
    | '/editor'
    | '/games'
    | '/library'
    | '/recordings'
    | '/settings'
    | '/uploads'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/diagnostics'
    | '/editor'
    | '/games'
    | '/library'
    | '/recordings'
    | '/settings'
    | '/uploads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  EditorRoute: typeof EditorRoute
  GamesRoute: typeof GamesRoute
  LibraryRoute: typeof LibraryRoute
  RecordingsRoute: typeof RecordingsRoute
  SettingsRoute: typeof SettingsRoute
  UploadsRoute: typeof UploadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  EditorRoute: EditorRoute,
  GamesRoute: GamesRoute,
  LibraryRoute: LibraryRoute,
  RecordingsRoute: RecordingsRoute,
  SettingsRoute: SettingsRoute,
  UploadsRoute: UploadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
